name: Trigger browser release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: Delwing/mudlet-map-browser
        token: ${{ secrets.BROWSER_ACCESS_TOKEN }}
        event-type: release
        client-payload: '{"message" : "Refer to https://github.com/Delwing/mudlet-map-reader for details."}'
