name: Upload release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Write version to file
        run: ${{ github.event.release.tag_name }} >> version
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'arkadia-mapsync.zip'
          exclusions: '*.git*'
      - name: Deploy to FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}